import { prisma } from "../lib/prisma"

async function main() {
  const services = [
    {
      slug: "lawn-maintenance",
      name: "Lawn Maintenance",
      description: "Servicio Principal",
      details:
        "Nuestro servicio principal de mantenimiento de césped, pensado para visitas recurrentes. Cada visita incluye corte (mowing) a la altura ideal según la temporada, recorte de orillas y bordes (trimming) alrededor de banquetas, cercas y obstáculos, y limpieza final con soplador (blower) de banquetas, entrada y patio. Mantiene el jardín ordenado y saludable de forma constante.",
      category: "CORE" as const,
      includes: ["Mowing", "Trimming", "Blower cleanup"],
      pricingUnit: "per visit",
      smallPrice: 60,
      mediumPrice: 80,
      largePrice: 110,
      biweeklySmallPrice: 65,
      biweeklyMediumPrice: 86,
      biweeklyLargePrice: 119,
      oneTimeSmallPrice: 85,
      oneTimeMediumPrice: 110,
      oneTimeLargePrice: 150,
      defaultPrice: 80,
      active: true,
      displayOrder: 10,
    },
    {
      slug: "clean-cut",
      name: "Clean Cut",
      description: "Upgrade Premium",
      details:
        "Versión premium del corte. Incluye todo lo del mantenimiento básico (corte, recorte y limpieza con soplador) y además bordes definidos con orilladora para un contorno marcado y limpio, junto con un acabado profesional con mayor atención al detalle. Recomendado para clientes que quieren el jardín siempre impecable.",
      category: "CORE" as const,
      includes: ["Todo lo anterior", "Bordes definidos", "Acabado pro"],
      pricingUnit: "per visit",
      smallPrice: 75,
      mediumPrice: 95,
      largePrice: 130,
      biweeklySmallPrice: 81,
      biweeklyMediumPrice: 102,
      biweeklyLargePrice: 140,
      oneTimeSmallPrice: 100,
      oneTimeMediumPrice: 130,
      oneTimeLargePrice: 175,
      defaultPrice: 95,
      active: true,
      displayOrder: 20,
    },
    {
      slug: "yard-cleanup",
      name: "Light Yard Cleanup",
      description: "Trabajos Extra",
      details:
        "Limpieza general del patio para ponerlo al día. Incluye recolección de hojas, rastrillado (rake) y soplado de áreas, y limpieza básica de desechos ligeros. El precio varía según el tamaño del jardín y la cantidad de material acumulado, por eso se cotiza en un rango (desde / hasta).",
      category: "CLEANUP" as const,
      includes: ["Hojas", "Rake + Blower", "Limpieza basica"],
      startingAtPrice: 120,
      maxRangePrice: 300,
      biweeklyStartingAtPrice: 130,
      oneTimeStartingAtPrice: 165,
      defaultPrice: 120,
      pricingUnit: "per visit",
      active: true,
      displayOrder: 30,
    },
    {
      slug: "addon-overgrown-grass",
      name: "Overgrown grass",
      description: "Add-on",
      details:
        "Cargo adicional cuando el césped está demasiado crecido, por falta de mantenimiento o una ausencia prolongada. Requiere pasadas extra, más tiempo de trabajo y mayor desgaste del equipo. Se cobra como complemento sobre el servicio de corte.",
      category: "ADD_ON" as const,
      startingAtPrice: 20,
      maxRangePrice: 50,
      biweeklyStartingAtPrice: 22,
      oneTimeStartingAtPrice: 28,
      memberDiscount: 15,
      pricingUnit: "per visit",
      active: true,
      displayOrder: 40,
    },
    {
      slug: "addon-bush-trimming",
      name: "Bush trimming",
      description: "Add-on",
      details:
        "Recorte y dado de forma a arbustos y setos. Incluye poda ligera para controlar el tamaño y mantener la forma, además de la limpieza de los recortes generados. Se agrega como complemento al servicio principal.",
      category: "ADD_ON" as const,
      startingAtPrice: 30,
      maxRangePrice: 80,
      biweeklyStartingAtPrice: 33,
      oneTimeStartingAtPrice: 42,
      memberDiscount: 15,
      pricingUnit: "per visit",
      active: true,
      displayOrder: 50,
    },
    {
      slug: "addon-bagging",
      name: "Bagging",
      description: "Add-on",
      details:
        "Embolsado y retiro del césped cortado y los recortes, en lugar de dejarlos triturados (mulched) sobre el jardín. Útil cuando se acumula mucho material o el cliente prefiere el patio sin restos visibles.",
      category: "ADD_ON" as const,
      startingAtPrice: 10,
      maxRangePrice: 25,
      biweeklyStartingAtPrice: 11,
      oneTimeStartingAtPrice: 14,
      memberDiscount: 15,
      pricingUnit: "per visit",
      active: true,
      displayOrder: 60,
    },
    {
      slug: "addon-debris-removal",
      name: "Debris removal",
      description: "Add-on",
      details:
        "Retiro y disposición de desechos del jardín: ramas, hojas acumuladas, basura y escombros ligeros. Se cobra según el volumen de material a retirar y se agrega como complemento al servicio.",
      category: "ADD_ON" as const,
      startingAtPrice: 20,
      maxRangePrice: 60,
      biweeklyStartingAtPrice: 22,
      oneTimeStartingAtPrice: 28,
      memberDiscount: 15,
      pricingUnit: "per visit",
      active: true,
      displayOrder: 70,
    },
  ]

  for (const service of services) {
    await prisma.serviceCatalog.upsert({
      where: { slug: service.slug },
      update: {
        name: service.name,
        description: service.description,
        details: service.details ?? null,
        category: service.category,
        includes: service.includes,
        pricingUnit: service.pricingUnit ?? null,
        defaultPrice: service.defaultPrice ?? null,
        smallPrice: service.smallPrice ?? null,
        mediumPrice: service.mediumPrice ?? null,
        largePrice: service.largePrice ?? null,
        biweeklySmallPrice: "biweeklySmallPrice" in service ? service.biweeklySmallPrice ?? null : null,
        biweeklyMediumPrice: "biweeklyMediumPrice" in service ? service.biweeklyMediumPrice ?? null : null,
        biweeklyLargePrice: "biweeklyLargePrice" in service ? service.biweeklyLargePrice ?? null : null,
        oneTimeSmallPrice: "oneTimeSmallPrice" in service ? service.oneTimeSmallPrice ?? null : null,
        oneTimeMediumPrice: "oneTimeMediumPrice" in service ? service.oneTimeMediumPrice ?? null : null,
        oneTimeLargePrice: "oneTimeLargePrice" in service ? service.oneTimeLargePrice ?? null : null,
        startingAtPrice: service.startingAtPrice ?? null,
        maxRangePrice: service.maxRangePrice ?? null,
        biweeklyStartingAtPrice: "biweeklyStartingAtPrice" in service ? service.biweeklyStartingAtPrice ?? null : null,
        oneTimeStartingAtPrice: "oneTimeStartingAtPrice" in service ? service.oneTimeStartingAtPrice ?? null : null,
        memberDiscount: service.memberDiscount ?? null,
        displayOrder: service.displayOrder,
        active: service.active,
      },
      create: {
        slug: service.slug,
        name: service.name,
        description: service.description,
        details: service.details ?? null,
        category: service.category,
        includes: service.includes,
        pricingUnit: service.pricingUnit ?? null,
        defaultPrice: service.defaultPrice ?? null,
        smallPrice: service.smallPrice ?? null,
        mediumPrice: service.mediumPrice ?? null,
        largePrice: service.largePrice ?? null,
        biweeklySmallPrice: "biweeklySmallPrice" in service ? service.biweeklySmallPrice ?? null : null,
        biweeklyMediumPrice: "biweeklyMediumPrice" in service ? service.biweeklyMediumPrice ?? null : null,
        biweeklyLargePrice: "biweeklyLargePrice" in service ? service.biweeklyLargePrice ?? null : null,
        oneTimeSmallPrice: "oneTimeSmallPrice" in service ? service.oneTimeSmallPrice ?? null : null,
        oneTimeMediumPrice: "oneTimeMediumPrice" in service ? service.oneTimeMediumPrice ?? null : null,
        oneTimeLargePrice: "oneTimeLargePrice" in service ? service.oneTimeLargePrice ?? null : null,
        startingAtPrice: service.startingAtPrice ?? null,
        maxRangePrice: service.maxRangePrice ?? null,
        biweeklyStartingAtPrice: "biweeklyStartingAtPrice" in service ? service.biweeklyStartingAtPrice ?? null : null,
        oneTimeStartingAtPrice: "oneTimeStartingAtPrice" in service ? service.oneTimeStartingAtPrice ?? null : null,
        memberDiscount: service.memberDiscount ?? null,
        displayOrder: service.displayOrder,
        active: service.active,
      },
    })
  }

  const plans = [
    {
      slug: "membership-small",
      name: "Membership Small",
      description: "Weekly service + VIP priority + 15% add-on discount",
      tier: "SMALL" as const,
      monthlyPrice: 220,
      visitsPerMonth: 4,
      addOnDiscount: 15,
      priorityScheduling: true,
      benefits: [
        { name: "Weekly Service", description: "4 visits per month" },
        { name: "VIP Priority", description: "Priority scheduling" },
        { name: "Add-on Discount", value: "15%", description: "Discount on all extras" },
      ],
      active: true,
    },
    {
      slug: "membership-medium",
      name: "Membership Medium",
      description: "Weekly service + VIP priority + 15% add-on discount",
      tier: "MEDIUM" as const,
      monthlyPrice: 300,
      visitsPerMonth: 4,
      addOnDiscount: 15,
      priorityScheduling: true,
      benefits: [
        { name: "Weekly Service", description: "4 visits per month" },
        { name: "VIP Priority", description: "Priority scheduling" },
        { name: "Add-on Discount", value: "15%", description: "Discount on all extras" },
      ],
      active: true,
    },
    {
      slug: "membership-large",
      name: "Membership Large",
      description: "Weekly service + VIP priority + 15% add-on discount",
      tier: "LARGE" as const,
      monthlyPrice: 420,
      visitsPerMonth: 4,
      addOnDiscount: 15,
      priorityScheduling: true,
      benefits: [
        { name: "Weekly Service", description: "4 visits per month" },
        { name: "VIP Priority", description: "Priority scheduling" },
        { name: "Add-on Discount", value: "15%", description: "Discount on all extras" },
      ],
      active: true,
    },
  ]

  for (const plan of plans) {
    await prisma.membershipPlan.upsert({
      where: { slug: plan.slug },
      update: {
        name: plan.name,
        description: plan.description,
        tier: plan.tier,
        monthlyPrice: plan.monthlyPrice,
        visitsPerMonth: plan.visitsPerMonth,
        addOnDiscount: plan.addOnDiscount,
        priorityScheduling: plan.priorityScheduling,
        benefits: plan.benefits,
        active: plan.active,
      },
      create: {
        slug: plan.slug,
        name: plan.name,
        description: plan.description,
        tier: plan.tier,
        monthlyPrice: plan.monthlyPrice,
        visitsPerMonth: plan.visitsPerMonth,
        addOnDiscount: plan.addOnDiscount,
        priorityScheduling: plan.priorityScheduling,
        benefits: plan.benefits,
        active: plan.active,
      },
    })
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (error) => {
    console.error(error)
    await prisma.$disconnect()
    process.exit(1)
  })
